//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperty
    {
        public int ProductID { get; set; }
        public int PropertyID { get; set; }
        public string ValueAsString { get; set; }
    
        public virtual Properties Properties { get; set; }
        public virtual Products Products { get; set; }
    }
}
